# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    services:
      postgres15:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_DB: gomin
          POSTGRES_PASSWORD: test
        ports:
          - 5435:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Install Task
      uses: arduino/setup-task@v1

    - name: Install atlas
      run: |
        set('git_tty', false);
        curl -sSf https://atlasgo.sh | sh

    - name: Migrate db
      run: task db.update

    - name: Test
      run: task test
