# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - uses: actions/checkout@v3

    - name: Start database and migrate
      run: |
        docker-compose up -d db
        docker-compose up migrate

    - name: Set GOPATH and PATH
      run: |
        echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
        echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
      shell: bash

    - name: Set build variables
      run: |
        echo "GOPROXY=https://proxy.golang.org" >> $GITHUB_ENV
        echo "GO111MODULE=on" >> $GITHUB_ENV

    - name: Run tests
      run: |
        go mod tidy
        go get -v ./...
        go test -test.v ./...
